services:
  todowebapi:
    image: ${DOCKER_REGISTRY-}todowebapi
    container_name: TodoWeb.Api
    restart: unless-stopped
    build:
      context: .
      dockerfile: TodoWebAPI/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081" 
  TodoWebapi-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: TodoWeb.Db
    environment:
      SA_PASSWORD: "SuperHardPassword!!"
      ACCEPT_EULA: "Y"
    ports:
        - 1433:1433
    volumes:
        -  ./.containers/database:/var/opt/mssql/data
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: SuperHardPassword!!
      MYSQL_DATABASE: tododb
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: SuperHardPassword!!!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  mysql_data: