services:
  todowebapi:
    image: ${DOCKER_REGISTRY-}todowebapi
    build:
      context: .
      dockerfile: TodoWebAPI/Dockerfile
    container_name: TodoWeb.Api
    restart: unless-stopped
    ports:
        - "80:8080"
        - "443:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
  TodoWebapi-db:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'SuperHardPassword!!'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    volumes:
        - ./mssql/data:/var/opt/mssql/data
        - ./mssql/log:/var/opt/mssql/log
        - ./mssql/secrets:/var/opt/mssql/secrets
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: SuperHardPassword!!
      MYSQL_DATABASE: tododb
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: SuperHardPassword!!!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  mysql_data:
  data:
  log:
  secrets: